### ISSUE TITLE
Add information about accessing TypoScript in extension

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-Typoscript#463]
AFAIK, this information is currently missing. Information about how to access TypoScript can be added, similar to the information on the [Flexform](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/FlexForms/Index.html) page. 

## todos

* [x] Access TypoScript from Extbase controllers
* [x] Access TypoScript from Fluid with Extbase controllers
* [ ] Access TypoScript with Extbase, but outside of controller (with ConfigurationManager?)
* [x] Access TypoScript outside of Extbase
* [x] Access TypoScript with Fluid, without Extbase

## Existing resources in TYPO3 documentation:

* [configuration in Extbase extensions](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/9a-Configuration/Index.html#configuration) (Extbase / Fluid book)
* [Extbase TypoScript reference](https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/b-ExtbaseReference/Index.html#typoscript-configuration) (Extbase / Fluid book)

## Existing resources outside of TYPO3 documentation

* [FluidTypo](https://fluidtypo3.org/documentation/templating-manual/templating/using-variables/typoscript-variables.html) nicely explains how the "settings" are used, see point **Solution**
* Stack Overflow: [How to get TYPO3 settings in the utility files?](https://stackoverflow.com/questions/30839907/how-to-get-typo3-settings-in-the-utility-files)
* access via ConfigurationManager, e.g. https://jainishsenjaliya.wordpress.com/2016/03/13/how-to-access-typoscript-settings-data-in-typo3-extension/

## Open questions

* should ConfigurationManager be used (and when?)
* can this always be used? Is it recommended?

`$GLOBALS['TSFE']->tmpl->setup['plugin.']['tx_xxxx.']['settings.']['storagePid'];`

https://stackoverflow.com/a/59598451/2444812

**Comment by linawolf** [comment]
Status after checking each item against the current manuals:

| Item | State |
|---|---|
| Access TypoScript from Extbase controllers | documented — [Access TypoScript in an extension](https://docs.typo3.org/permalink/t3tsref:extdev-access-typoscript), section "Extbase controllers" |
| Access TypoScript from Fluid with Extbase controllers | documented — same page, section "Fluid" |
| Access TypoScript with Extbase, but outside of controller | **still open**, moved to TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#6816 |
| Access TypoScript outside of Extbase | documented in TYPO3 Explained, linked from here as of #1835 |
| Access TypoScript with Fluid, without Extbase | documented as [`FLUIDTEMPLATE.settings`](https://docs.typo3.org/permalink/t3tsref:cobj-fluidtemplate-properties-settings), linked from here as of #1835 |

#1835 adds the two missing links and gives page TSconfig a section of its
own, so the chapter no longer stops after the two Extbase cases.

The third item turned out not to be a pure writing task.
`ConfigurationManagerInterface` carries the annotation
`@internal only to be used within Extbase, not part of TYPO3 Core API.`, and
`getConfiguration()` a matching note: "this is a low level method and only
makes sense to be used by Extbase internally". That appears to answer this
issue's own open question from 2021 — "should ConfigurationManager be used
(and when?)" — with "no", but what to recommend instead needs a decision.
That is TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#6816.

One note for anyone arriving here from a search engine: the snippet in the
description, `$GLOBALS['TSFE']->tmpl->setup[...]`, no longer works —
`TypoScriptFrontendController` has no `tmpl` property any more. The
replacement is
`$request->getAttribute('frontend.typoscript')->getSetupArray()`.

Once #1835 is merged, this issue could be reduced to the single remaining
item, or closed in favour of #6816.

**Comment by sypets** [comment]
Thank you @linawolf

**Comment by linawolf** [comment]
I think this can be closed then
